apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 # tells deployment run 2 pods match the template
  template:   #This is a pod template to manipulate actual pod
    metadata:
      labels:
        app: nginx
    spec:
      containers: # Here is a array for container's details
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80  
